/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class CUIPSDGradient, CUIShapeEffectPreset;
@interface CSIGenerator : NSObject
{
    NSMutableArray *_slices;
    NSMutableArray *_bitmaps;
    NSMutableArray *_metrics;
    BOOL _allowsMultiPassEncoding;
    short _layout;
    NSData *_rawData;
    int _exifOrientation;
    unsigned long long _rowbytes;
    NSString *_assetPackIdentifier;
    NSSet *_externalTags;
    CGRect _externalReferenceFrame;
    unsigned short _linkLayout;
}

+ (int)fileEncoding;
+ (void)setFileEncoding:(int)arg1;

@property(nonatomic) BOOL allowsMultiPassEncoding; // @synthesize allowsMultiPassEncoding=_allowsMultiPassEncoding;
@property(nonatomic) CGRect alphaCroppedFrame; // @synthesize alphaCroppedFrame=_alphaCroppedFrame;
@property(nonatomic) CGSize originalUncroppedSize; // @synthesize originalUncroppedSize=_originalUncroppedSize;
@property(nonatomic) int exifOrientation; // @synthesize exifOrientation=_exifOrientation;
@property(copy, nonatomic) NSDate *modtime; // @synthesize modtime=_modtime;
@property(nonatomic) double opacity; // @synthesize opacity=_opacity;
@property(nonatomic) int blendMode; // @synthesize blendMode=_blendMode;
@property(retain, nonatomic) CUIShapeEffectPreset *effectPreset; // @synthesize effectPreset=_effectPreset;
@property(readonly, nonatomic) NSArray *references; // @synthesize references=_references;
@property(nonatomic) unsigned int pixelFormat; // @synthesize pixelFormat=_pixelFormat;
@property(nonatomic) unsigned int scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(retain, nonatomic) CUIPSDGradient *gradient; // @synthesize gradient=_gradient;
@property(nonatomic) short colorSpaceID; // @synthesize colorSpaceID=_colorSpaceID;
@property(nonatomic, getter=isExcludedFromContrastFilter) BOOL excludedFromContrastFilter; // @synthesize excludedFromContrastFilter=_isExcludedFromFilter;
@property(nonatomic) long long templateRenderingMode; // @synthesize templateRenderingMode=_templateRenderingMode;
@property(nonatomic) BOOL isVectorBased; // @synthesize isVectorBased=_isVectorBased;
@property(nonatomic) BOOL isRenditionFPO; // @synthesize isRenditionFPO=_isFPOHint;
@property(copy, nonatomic) NSString *utiType; // @synthesize utiType=_utiType;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;

- (instancetype)initWithInternalReferenceRect:(CGRect)arg1 layout:(short)arg2;
- (instancetype)initWithLayerStackData:(id)arg1 withCanvasSize:(struct CGSize)arg2;
- (instancetype)initWithExternalReference:(id)arg1 tags:(id)arg2;
- (instancetype)initWithRawData:(id)arg1 pixelFormat:(unsigned int)arg2 layout:(short)arg3;
- (instancetype)initWithShapeEffectPreset:(id)arg1 forScaleFactor:(unsigned int)arg2;
- (instancetype)initWithCanvasSize:(CGSize)arg1 sliceCount:(unsigned int)arg2 layout:(short)arg3;

- (NSData *)CSIRepresentationWithCompression:(BOOL)compress;

- (void)addLayerReference:(id)arg1;
- (void)addMetrics:(CDStruct_1ba92a5e)arg1;
- (void)addSliceRect:(CGRect)sliceRect;
- (void)addBitmap:(id)arg1; // bitmapwrapper

//! Don't use these:
- (unsigned long long)writeExternalLinkToData:(NSData *)data;
- (unsigned long long)writeRawDataToData:(NSData *)data;
- (unsigned long long)writeGradientToData:(NSData *)data;
//- (void)_addNodes:(id)arg1 toNodeList:(struct _csigradientdatanode *)arg2;
- (unsigned long long)writeBitmap:(id)arg1 toData:(NSData *)data compress:(BOOL)compress;
- (unsigned long long)writeResourcesToData:(id)arg1;
- (void)writeHeader:(struct csiheader *)header toData:(NSdata *)data;
- (void)formatCSIHeader:(struct csiheader *)header;

@end

