//
//  CUICatalog.h
//  ThemeKit
//
//  Created by Alexander Zielenski on 9/26/19.
//  Copyright © 2019 Alex Zielenski. All rights reserved.
//

#ifndef CUICatalog_h
#define CUICatalog_h

/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 8, 2019 at 1:24:47 PM Eastern European Standard Time
* Operating System: Version 12.1 (Build 16B92)
* Image Source: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSMapTable, NSBundle, NSString, NSCache;

@interface CUICatalog : NSObject {

    unsigned long long _storageRef;
    NSMapTable* _storageMapTable;
    NSBundle* _bundle;
    NSString* _assetStoreName;
    NSCache* _lookupCache;
    NSCache* _negativeCache;
    unsigned _purgeWhenFinished : 1;
    unsigned _fileHasDisplayGamutInKeySpace : 2;
    unsigned _reserved : 28;

}

@property (assign,nonatomic) unsigned long long storageRef;              //@synthesize storageRef=_storageRef - In the implementation block
+(CGColorRef)newColorByAdjustingLightnessOfColor:(CGColorRef)arg1 darker:(BOOL)arg2 ;
+(id)systemUICatalog;
+(id)bestMatchUsingObjects:(id)arg1 getAttributeValueUsing:(/*^block*/id)arg2 scaleFactor:(double)arg3 deviceIdiom:(long long)arg4 deviceSubtype:(unsigned long long)arg5 displayGamut:(long long)arg6 deploymentTarget:(long long)arg7 layoutDirection:(long long)arg8 sizeClassHorizontal:(long long)arg9 sizeClassVertical:(long long)arg10 memoryClass:(long long)arg11 graphicsFeatureSetClass:(long long)arg12 graphicsFallBackOrder:(id)arg13 deviceSubtypeFallBackOrder:(id)arg14 ;
+(id)defaultUICatalog;
+(id)bestMatchUsingImages:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 ;
+(id)bestMatchUsingImages:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 sizeClassHorizontal:(long long)arg5 sizeClassVertical:(long long)arg6 ;
+(id)bestMatchUsingImages:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 displayGamut:(unsigned long long)arg4 deviceSubtype:(unsigned long long)arg5 sizeClassHorizontal:(long long)arg6 sizeClassVertical:(long long)arg7 ;
+(id)defaultUICatalogForBundle:(id)arg1 ;
+(id)bestMatchUsingImages:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(unsigned long long)arg5 layoutDirection:(unsigned long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 ;
+(BOOL)isValidAssetStorageWithURL:(id)arg1 ;
+(BOOL)isValidLCRWithBytes:(const void*)arg1 length:(unsigned long long)arg2 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 memoryClass:(long long)arg9 graphicsClass:(long long)arg10 ;
-(id)_recognitionImageWithName:(id)arg1 ;
-(id)_recognitionObjectWithName:(id)arg1 ;
-(void)setStorageRef:(unsigned long long)arg1 ;
-(unsigned long long)storageRef;
-(id)_themeStore;
-(id)_baseKeyForName:(id)arg1 ;
-(unsigned long long)_storageRefForRendition:(id)arg1 representsODRContent:(BOOL*)arg2 ;
-(id)_baseImageKeyForName:(id)arg1 ;
-(id)allImageNames;
-(id)lookupCache;
-(id)negativeCache;
-(void)_resourceUnPinnedNotification:(id)arg1 ;
-(id)_resolvedRenditionKeyForName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 memoryClass:(unsigned long long)arg9 graphicsClass:(unsigned long long)arg10 appearanceIdentifier:(long long)arg11 graphicsFallBackOrder:(id)arg12 deviceSubtypeFallBackOrder:(id)arg13 withBaseKeySelector:(SEL)arg14 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 appearanceName:(id)arg5 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 appearanceName:(id)arg9 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 appearanceName:(id)arg4 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 sizeClassHorizontal:(long long)arg5 sizeClassVertical:(long long)arg6 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 sizeClassHorizontal:(long long)arg5 sizeClassVertical:(long long)arg6 appearanceName:(id)arg7 ;
-(long long)_appearanceIdentifierForName:(id)arg1 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 memoryClass:(unsigned long long)arg9 graphicsClass:(unsigned long long)arg10 appearanceIdentifier:(long long)arg11 graphicsFallBackOrder:(id)arg12 deviceSubtypeFallBackOrder:(id)arg13 ;
-(id)_imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 memoryClass:(unsigned long long)arg9 graphicsClass:(unsigned long long)arg10 appearanceIdentifier:(long long)arg11 graphicsFallBackOrder:(id)arg12 deviceSubtypeFallBackOrder:(id)arg13 ;
-(id)iconImageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 desiredSize:(CGSize)arg9 appearanceName:(id)arg10 ;
-(id)_baseMultisizeImageSetKeyForName:(id)arg1 ;
-(id)_resolvedRenditionKeyFromThemeRef:(unsigned long long)arg1 withBaseKey:(id)arg2 scaleFactor:(double)arg3 deviceIdiom:(long long)arg4 deviceSubtype:(unsigned long long)arg5 displayGamut:(long long)arg6 layoutDirection:(long long)arg7 sizeClassHorizontal:(long long)arg8 sizeClassVertical:(long long)arg9 memoryClass:(unsigned long long)arg10 graphicsClass:(unsigned long long)arg11 graphicsFallBackOrder:(id)arg12 deviceSubtypeFallBackOrder:(id)arg13 iconSizeIndex:(unsigned long long)arg14 appearanceIdentifier:(unsigned long long)arg15 ;
-(BOOL)imageExistsWithName:(id)arg1 ;
-(id)_dataWithName:(id)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 memoryClass:(unsigned long long)arg4 graphicsClass:(unsigned long long)arg5 appearanceIdentifier:(long long)arg6 graphicsFallBackOrder:(id)arg7 deviceSubtypeFallBackOrder:(id)arg8 ;
-(id)dataWithName:(id)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 memoryClass:(unsigned long long)arg4 graphicsClass:(unsigned long long)arg5 appearanceIdentifier:(long long)arg6 graphicsFallBackOrder:(id)arg7 deviceSubtypeFallBackOrder:(id)arg8 ;
-(id)dataWithName:(id)arg1 appearanceName:(id)arg2 ;
-(id)_baseAtlasKeyForName:(id)arg1 ;
-(id)_baseAtlasContentsKeyForName:(id)arg1 ;
-(unsigned long long)_themeRef;
-(id)_namedImageAtlasWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 displayGamut:(long long)arg4 deviceSubtype:(unsigned long long)arg5 memoryClass:(unsigned long long)arg6 graphicsClass:(unsigned long long)arg7 graphicsFallBackOrder:(id)arg8 deviceSubtypeFallBackOrder:(id)arg9 ;
-(id)namedImageAtlasWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 displayGamut:(long long)arg4 deviceSubtype:(unsigned long long)arg5 memoryClass:(unsigned long long)arg6 graphicsClass:(unsigned long long)arg7 graphicsFallBackOrder:(id)arg8 deviceSubtypeFallBackOrder:(id)arg9 ;
-(id)parentNamedImageAtlasForImageNamed:(id)arg1 scaleFactor:(double)arg2 displayGamut:(unsigned long long)arg3 ;
-(CGPDFDocumentRef)pdfDocumentWithName:(id)arg1 appearanceName:(id)arg2 ;
-(id)namedVectorImageWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 layoutDirection:(long long)arg4 ;
-(id)namedVectorImageWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 layoutDirection:(long long)arg4 appearanceName:(id)arg5 ;
-(id)namedVectorImageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 appearanceName:(id)arg9 ;
-(id)_baseVectorRenditionKey:(id)arg1 ;
-(id)_namedVectorImageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 appearanceIdentifier:(long long)arg9 ;
-(id)layerStackWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 ;
-(id)layerStackWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 sizeClassHorizontal:(long long)arg5 sizeClassVertical:(long long)arg6 ;
-(id)_layerStackWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 sizeClassHorizontal:(long long)arg5 sizeClassVertical:(long long)arg6 ;
-(id)_defaultAssetRenditionKey:(id)arg1 ;
-(id)_defaultLayerStackWithScaleFactor:(double)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 sizeClassHorizontal:(long long)arg4 sizeClassVertical:(long long)arg5 ;
-(id)_defaultNamedAssetWithScaleFactor:(double)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 sizeClassHorizontal:(long long)arg4 sizeClassVertical:(long long)arg5 ;
-(id)_namedLookupWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 ;
-(id)namedLookupWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 sizeClassHorizontal:(long long)arg5 sizeClassVertical:(long long)arg6 ;
-(id)_baseTextureKeyForName:(id)arg1 ;
-(id)_namedTextureWithName:(id)arg1 scaleFactor:(double)arg2 appearanceName:(id)arg3 ;
-(id)namedTextureWithName:(id)arg1 scaleFactor:(double)arg2 appearanceName:(id)arg3 ;
-(id)_namedTextureWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 appearanceName:(id)arg4 ;
-(id)namedTextureWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 appearanceName:(id)arg4 ;
-(id)_baseColorKeyForName:(id)arg1 ;
-(id)_colorWithName:(id)arg1 displayGamut:(long long)arg2 deviceIdiom:(long long)arg3 appearanceName:(id)arg4 ;
-(id)colorWithName:(id)arg1 displayGamut:(long long)arg2 deviceIdiom:(long long)arg3 appearanceName:(id)arg4 ;
-(id)colorWithName:(id)arg1 displayGamut:(long long)arg2 appearanceName:(id)arg3 ;
-(id)_modelWithName:(id)arg1 ;
-(id)_baseRecognitionGroupImageSetKeyForName:(id)arg1 ;
-(id)_baseRecognitionObjectKeyForName:(id)arg1 ;
-(BOOL)canGetShapeEffectRenditionWithKey:(id)arg1 ;
-(BOOL)_effectStyle:(unsigned long long*)arg1 state:(long long*)arg2 presentationState:(long long*)arg3 value:(long long*)arg4 resolution:(unsigned long long*)arg5 dimension1:(unsigned long long*)arg6 fromStyleConfiguration:(id)arg7 ;
-(id)renditionKeyForShapeEffectPresetWithStylePresetName:(id)arg1 state:(long long)arg2 presentationState:(long long)arg3 value:(long long)arg4 resolution:(unsigned long long)arg5 dimension1:(unsigned long long)arg6 ;
-(id)renditionKeyForShapeEffectPresetWithStyleID:(unsigned long long)arg1 state:(long long)arg2 presentationState:(long long)arg3 value:(long long)arg4 resolution:(unsigned long long)arg5 dimension1:(unsigned long long)arg6 ;
-(id)renditionKeyForShapeEffectPresetForStylePresetName:(id)arg1 styleConfiguration:(id)arg2 ;
-(id)newShapeEffectPresetWithRenditionKey:(id)arg1 ;
-(id)newShapeEffectPresetForStylePresetName:(id)arg1 styleConfiguration:(id)arg2 ;
-(BOOL)requiredDrawOfUnstyledGlyphs:(const unsigned short*)arg1 atPositions:(const CGPoint*)arg2 inContext:(CGContextRef)arg3 withFont:(CTFontRef)arg4 count:(unsigned long long)arg5 ;
-(id)newTextEffectStackForStylePresetName:(id)arg1 styleConfiguration:(id)arg2 foregroundColor:(CGColorRef)arg3 ;
-(BOOL)fillStyledPath:(CGPathRef)arg1 inContext:(CGContextRef)arg2 stylePresetName:(id)arg3 styleConfiguration:(id)arg4 ;
-(BOOL)_doStyledQuartzDrawingInContext:(CGContextRef)arg1 inBounds:(CGRect)arg2 stylePresetName:(id)arg3 styleConfiguration:(id)arg4 drawingHandler:(/*^block*/id)arg5 ;
-(BOOL)hasStylePresetWithName:(id)arg1 styleConfiguration:(id)arg2 ;
-(CGColorRef)equivalentForegroundColorForStylePresetWithName:(id)arg1 styleConfiguration:(id)arg2 baseForegroundColor:(CGColorRef)arg3 ;
-(id)newShapeEffectStackForStylePresetName:(id)arg1 styleConfiguration:(id)arg2 foregroundColor:(CGColorRef)arg3 ;
-(id)initWithName:(id)arg1 fromBundle:(id)arg2 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 appearanceName:(id)arg3 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 layoutDirection:(long long)arg4 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 layoutDirection:(long long)arg4 appearanceName:(id)arg5 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 memoryClass:(unsigned long long)arg9 graphicsClass:(unsigned long long)arg10 graphicsFallBackOrder:(id)arg11 deviceSubtypeFallBackOrder:(id)arg12 ;
-(id)iconImageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 desiredSize:(CGSize)arg9 ;
-(BOOL)imageExistsWithName:(id)arg1 scaleFactor:(double)arg2 ;
-(id)dataWithName:(id)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 memoryClass:(unsigned long long)arg4 graphicsClass:(unsigned long long)arg5 graphicsFallBackOrder:(id)arg6 deviceSubtypeFallBackOrder:(id)arg7 ;
-(id)namedImageAtlasWithName:(id)arg1 scaleFactor:(double)arg2 ;
-(id)namedImageAtlasWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 ;
-(id)namedImageAtlasWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(unsigned long long)arg3 ;
-(id)parentNamedImageAtlastForImageNamed:(id)arg1 scaleFactor:(double)arg2 ;
-(void)preloadNamedAtlasWithScaleFactor:(double)arg1 andNames:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)enumerateNamedLookupsUsingBlock:(/*^block*/id)arg1 ;
-(CGPDFDocumentRef)pdfDocumentWithName:(id)arg1 ;
-(id)layerStackWithName:(id)arg1 ;
-(id)layerStackWithName:(id)arg1 scaleFactor:(double)arg2 ;
-(id)defaultNamedAssetWithScaleFactor:(double)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 sizeClassHorizontal:(long long)arg4 sizeClassVertical:(long long)arg5 ;
-(id)namedLookupWithName:(id)arg1 scaleFactor:(double)arg2 ;
-(id)namedTextureWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(long long)arg3 ;
-(id)iconImageWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(unsigned long long)arg3 layoutDirection:(long long)arg4 desiredSize:(CGSize)arg5 ;
-(id)iconImageWithName:(id)arg1 scaleFactor:(double)arg2 displayGamut:(unsigned long long)arg3 layoutDirection:(long long)arg4 desiredSize:(CGSize)arg5 appearanceName:(id)arg6 ;
-(id)colorWithName:(id)arg1 displayGamut:(long long)arg2 ;
-(id)modelWithName:(id)arg1 ;
-(id)appearanceNames;
-(id)_nameForAppearanceIdentifier:(long long)arg1 ;
-(long long)artVariantIDOrZero;
-(BOOL)strokeStyledPath:(CGPathRef)arg1 inContext:(CGContextRef)arg2 stylePresetName:(id)arg3 styleConfiguration:(id)arg4 ;
-(BOOL)fillStyledRect:(CGRect)arg1 inContext:(CGContextRef)arg2 stylePresetName:(id)arg3 styleConfiguration:(id)arg4 ;
-(CGColorRef)equivalentForegroundColorForStylePresetWithName:(id)arg1 styleConfiguration:(id)arg2 ;
-(int)blendModeForStylePresetWithName:(id)arg1 styleConfiguration:(id)arg2 ;
-(BOOL)drawGlyphs:(const unsigned short*)arg1 atPositions:(const CGPoint*)arg2 inContext:(CGContextRef)arg3 withFont:(CTFontRef)arg4 count:(unsigned long long)arg5 stylePresetName:(id)arg6 styleConfiguration:(id)arg7 foregroundColor:(CGColorRef)arg8 ;
-(id)namedTextureWithName:(id)arg1 scaleFactor:(double)arg2 ;
-(id)namedRecognitionGroupWithName:(id)arg1 ;
-(void)dealloc;
-(id)debugDescription;
//-(psdGradientColor)styledInsetsForStylePresetName:(id)arg1 styleConfiguration:(id)arg2 foregroundColor:(CGColorRef)arg3 scale:(double)arg4 ;
-(id)imageByStylingImage:(CGImageRef)arg1 stylePresetName:(id)arg2 styleConfiguration:(id)arg3 foregroundColor:(CGColorRef)arg4 scale:(double)arg5 ;
-(id)imagesWithName:(id)arg1 ;
-(id)imageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 ;
-(id)initWithURL:(id)arg1 error:(id*)arg2 ;
-(id)initWithBytes:(const void*)arg1 length:(unsigned long long)arg2 error:(id*)arg3 ;
-(id)defaultLayerStackWithScaleFactor:(double)arg1 deviceIdiom:(long long)arg2 deviceSubtype:(unsigned long long)arg3 sizeClassHorizontal:(long long)arg4 sizeClassVertical:(long long)arg5 ;
-(BOOL)hasStylePresetWithName:(id)arg1 ;
-(id)initWithName:(id)arg1 fromBundle:(id)arg2 error:(id*)arg3 ;
-(id)namedLookupWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 ;
-(id)namedVectorImageWithName:(id)arg1 scaleFactor:(double)arg2 deviceIdiom:(long long)arg3 deviceSubtype:(unsigned long long)arg4 displayGamut:(long long)arg5 layoutDirection:(long long)arg6 sizeClassHorizontal:(long long)arg7 sizeClassVertical:(long long)arg8 ;
-(id)dataWithName:(id)arg1 ;
-(id)colorWithName:(id)arg1 displayGamut:(long long)arg2 deviceIdiom:(long long)arg3 ;
-(void)clearCachedImageResources;
@end

#endif /* CUICatalog_h */
