/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/CUIThemeRendition.h>
#import <CoreUI/CUIRenditionKey.h>
#import <CoreUI/Metadata/CUIRenditionMetrics.h>
#import <CoreUI/Metadata/CUIRenditionSliceInformation.h>

@class CUIStructuredThemeStore;

@protocol _CUIInternalLinkRenditionSourceProvider <NSObject>

- (CUIThemeRendition *)renditionWithKey:(struct renditionkeytoken *)key;

@end

// Not exported
@interface _CUIInternalLinkRendition : CUIThemeRendition
{
    unsigned int _nimages;
    CGRect _imageRect[16];
    CGImageRef _image[16];
    CGImageRef _unslicedImage;
    CUIRenditionMetrics *_renditionMetrics;
    CUIRenditionSliceInformation *_sliceInformation;
    CGRect _frame;
    CUIStructuredThemeStore *_sourceProvider;
    CUIRenditionKey *_referenceKey;
    CGSize _originalUncroppedSize;
    CGRect _alphaCroppedFrame;
}

- (void)_fillOutImageSlices;
- (CGImageRef)_sourceImage;
- (CGRect)_destinationFrame;
- (void)_setStructuredThemeStore:(id <_CUIInternalLinkRenditionSourceProvider>)sourceProvider;

@end

