/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/CUIThemeRendition.h>
#import <CoreUI/Metadata/CUIRenditionMetrics.h>
#import <CoreUI/Metadata/CUIRenditionSliceInformation.h>

// Not exported
@interface _CUIRawPixelRendition : CUIThemeRendition
{
    unsigned int _nimages;
    CGImageRef _image[16];
    CGImageRef _unslicedImage;
    CUIRenditionMetrics *_renditionMetrics;
    CUIRenditionSliceInformation *_sliceInformation;
}
@end

