/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/CUIThemeRendition.h>
#import <CoreUI/Rendering/CUIThemeGradient.h>

struct _csigradientdatanode {
    unsigned int magic; // OPCT, MDPT, COLR, OPCD (lead out opacity)
    float location;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
    double _field10;
};

//! These are just guesed fields, verify them
struct __CUIThemeGradientRenditionInitializerStruct {
    unsigned int style;
    double angle;
    void *gradient; // CUIThemeGradient, ARC forbits objc objects in a struct
};

// Not exported
@interface _CUIThemeGradientRendition : CUIThemeRendition
{
    CUIThemeGradient *gradient;
    double gradientAngle;
}

+ (struct __CUIThemeGradientRenditionInitializerStruct)_parseGradientInfoFromCSIHeader:(const struct csiheader *)arg1;
+ (id)_nodesFromNodeList:(struct _csigradientdatanode *)arg1 count:(unsigned long long)arg2 header:(const struct csiheader *)arg3;

@end

