/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/CUIThemeRendition.h>
#import <CoreUI/Metadata/CUIRenditionMetrics.h>
#import <CoreUI/Metadata/CUIRenditionSliceInformation.h>

@class _CSIRenditionBlockData;

// Not exported
@interface _CUIThemePixelRendition : CUIThemeRendition
{
    unsigned int nimages;
    CGImageRef image[16];
    CGImageRef unslicedImage;
    CUIRenditionMetrics *_renditionMetrics;
    CUIRenditionSliceInformation *_sliceInformation;
    _CSIRenditionBlockData *_cachedBlockDataBGRX;
    _CSIRenditionBlockData *_cachedBlockDataRGBX;
    unsigned long long _sourceRowbytes;
    NSMutableArray *_layers;
}

- (unsigned long long)sourceRowbytes;
- (void)setSharedBlockData:(_CSIRenditionBlockData *)arg1;
- (_CSIRenditionBlockData *)copySharedBlockDataWithPixelFormat:(int)arg1;

- (CGImageRef)newImageFromCSIDataSlice:(struct slice)arg1 ofBitmap:(struct csibitmap *)arg2 usingColorspace:(CGColorSpaceRef)arg3;

@end

