//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

typedef struct {
    unsigned int colorEdgePixel:2;
    unsigned int opacityEdgePixel:2;
    unsigned int isDithered:1;
    unsigned int reserved:3;
} _gradientFlags;

@interface CUIPSDGradientEvaluator : NSObject <NSCoding, NSCopying>
{
    NSArray *colorStops;
    NSArray *colorMidpointLocations;
    NSArray *opacityStops;
    NSArray *opacityMidpointLocations;
    double smoothingCoefficient;
    id /*struct _psdGradientColor*/ fillColor;
    int blendMode;
    _gradientFlags pgeFlags;
}

+ (void)initialize;
@property(nonatomic) CGBlendMode blendMode; // @synthesize blendMode;
- (void)customizeForDistance:(CGFloat)arg1;
- (void)setFillCoefficient:(CGFloat)arg1;
- (void)setSmoothingCoefficient:(CGFloat)arg1;
- (void)setOpacityStops:(NSArray *)arg1 midpoints:(NSArray *)arg2;
- (void)setColorStops:(NSArray *)arg1 midpoints:(NSArray *)arg2;
- (NSString *)description;
- (BOOL)hasEdgePixel;
- (struct _psdGradientColor)fillColor;
- (CGFloat)fillCoefficient;
- (BOOL)isDithered;
- (CGFloat)smoothingCoefficient;
- (NSArray *)opacityMidpointLocations;
- (NSArray *)opacityStops;
- (NSArray *)colorMidpointLocations;
- (NSArray *)colorStops;
- (struct _psdGradientColor)_smoothedGradientColorAtLocation:(double)arg1;
- (double)_smoothedInterpolationOfLocation:(double)arg1 betweenLower:(double)arg2 upper:(double)arg3 scaledMidpoint:(double)arg4;
- (void)dealloc;
- (id)initWithColorStops:(NSArray *)arg1 colorMidpoints:(NSArray *)arg2 opacityStops:(NSArray *)arg3 opacityMidpoints:(NSArray *)arg4 smoothingCoefficient:(CGFloat)arg5 fillColor:(struct _psdGradientColor)arg6 dither:(BOOL)arg7;
- (id)initWithColorStops:(NSArray *)arg1 colorMidpoints:(NSArray *)arg2 opacityStops:(NSArray *)arg3 opacityMidpoints:(NSArray *)arg4 smoothingCoefficient:(CGFloat)arg5 fillCoefficient:(CGFloat)arg6;
- (void)_createOrderedStops:(id *)arg1 midpoints:(id *)arg2 fromStops:(id)arg3 midpoints:(id)arg4 edgePixel:(long long *)arg5;
- (id)_cleanedUpMidpointLocationsFromLocations:(id)arg1;
- (void)_applyContrastFilterToColorsWithColorSpace:(struct CGColorSpace *)arg1;

@end

