/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

// Not exported
@interface CUIRenditionSliceInformation : NSObject <NSCopying>
{
    //!TODO document this type
    long long _renditionType;
    double _boundaries[4];
    CGRect _destinationRect;
    NSEdgeInsets _edgeInsets;
}

@property(readonly, nonatomic) NSEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(readonly, nonatomic) struct CGRect destinationRect; // @synthesize destinationRect=_destinationRect;
@property(readonly, nonatomic) long long renditionType; // @synthesize renditionType=_renditionType;

- (CGFloat)positionOfSliceBoundary:(unsigned long long)boundary;
- (CGSize)_bottomRightCapSize;
- (CGSize)_topLeftCapSize;

- (instancetype)initWithRenditionType:(long long)type destinationRect:(CGRect)rect topLeftInset:(CGSize)tl bottomRightInset:(CGSize)br;
- (instancetype)initWithSliceInformation:(CUIRenditionSliceInformation *)slices destinationRect:(CGRect)rect;

@end

