/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

// Not exported
@interface CUIRenditionMetrics : NSObject
{
    CGSize _imageSize;
    CGSize _edgeBottomLeftMargin;
    CGSize _edgeTopRightMargin;
    CGSize _contentBottomLeftMargin;
    CGSize _contentTopRightMargin;
    double _baseline;
    double _scale;
    struct crmFlags {
        unsigned int scalesVertically:1;
        unsigned int scalesHorizontally:1;
        unsigned int reserved:14;
    } _crmFlags;
}

- (BOOL)hasAlignmentEdgeMargins;
- (BOOL)hasOpaqueContentBounds;

- (CGRect)insetContentRectWithMetrics:(CGRect)contentRect;
- (CGRect)insetRectWithMetrics:(CGRect)edgeRect;
- (CGRect)contentRect;
- (CGRect)edgeRect;

- (BOOL)scalesHorizontally;
- (BOOL)scalesVertically;
- (CGFloat)scale;
- (CGFloat)baseline;

- (CGSize)contentTopRightMargin;
- (CGSize)contentBottomLeftMargin;
- (CGSize)edgeTopRightMargin;
- (CGSize)edgeBottomLeftMargin;
- (CGSize)imageSize;

- (instancetype)initWithImageSize:(CGSize)size edgeBottomLeft:(CGSize)ebl edgeTopRight:(CGSize)etr contentBottomLeft:(CGSize)cbl contentTopRight:(CGSize)ctr baseline:(CGFloat)baseline scalesVertically:(BOOL)vertically scalesHorizontally:(BOOL)horizontally scale:(CGFloat)scaleFactor;
- (instancetype)initwithImageSize:(CGSize)arg1 scale:(CGFloat)arg2;

@end

