/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */


#import <CoreUI/Rendering/PSD/CUIPSDGradientEvaluator.h>

@interface CUIPSDGradient : NSObject
{
    CUIPSDGradientEvaluator *evaluator;
    CGFloat drawingAngle;
    CUIGradientStyle gradientStyle;
}
@property CUIGradientStyle gradientStyle; // @synthesize gradientStyle;
@property CGFloat drawingAngle; // @synthesize drawingAngle;
@property(retain) CUIPSDGradientEvaluator *evaluator; // @synthesize evaluator;

+ (instancetype)cuiPSDGradientWithColors:(NSArray *)colors locations:(NSArray<NSNumber *> *)locations midpointLocations:(NSArray<NSNumber *> *)arg3 angle:(CGFloat)angle style:(CUIGradientStyle)style;
+ (instancetype)cuiPSDGradientWithColors:(NSArray *)colors locations:(NSArray<NSNumber *> *)locations midpointLocations:(NSArray<NSNumber *> *)arg3 angle:(CGFloat)angle isRadial:(BOOL)radial;
+ (instancetype)getMidpointLocationFromArray:(NSArray *)locations atIndex:(CFIndex)index withPolicy:(int)policy;

- (instancetype)initWithEvaluator:(CUIPSDGradientEvaluator *)evaluator drawingAngle:(CGFloat)angle gradientStyle:(CUIGradientStyle)style;

@end

