/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/Rendering/PSD/CUIPSDGradientStop.h>

@interface CUIPSDGradientOpacityStop : CUIPSDGradientStop <NSCoding>
{
    double opacity;
}

+ (id)opacityStopWithLocation:(CGFloat)arg1 opacity:(CGFloat)arg2;
+ (void)initialize;
- (id)description;
- (BOOL)isOpacityStop;
- (CGFloat)opacityLocation;
- (CGFloat)opacity;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithLocation:(CGFloat)arg1 opacity:(CGFloat)arg2;

@end

