/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/Rendering/PSD/CUIPSDGradientStop.h>

@interface CUIPSDGradientColorStop : CUIPSDGradientStop <NSCoding>
{
    struct _psdGradientColor gradientColor;
}

+ (id)colorStopWithLocation:(CGFloat)arg1 gradientColor:(struct _psdGradientColor)arg2;
+ (void)initialize;
- (id)description;
- (BOOL)isColorStop;
- (CGFloat)colorLocation;
- (struct _psdGradientColor)gradientColor;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithLocation:(CGFloat)arg1 gradientColor:(struct _psdGradientColor)arg2;

@end

