/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

// Not exported
@interface CUIPSDGradientStop : NSObject <NSCoding, NSCopying>
{
    double location;
}

- (BOOL)isOpacityStop;
- (BOOL)isColorStop;
- (BOOL)isDoubleStop;
- (void)setLocation:(CGFloat)arg1;
- (CGFloat)location;

- (instancetype)initWithLocation:(CGFloat)arg1;

@end

