/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/Rendering/PSD/CUIPSDGradientOpacityStop.h>

// Not exported
@interface CUIPSDGradientDoubleOpacityStop : CUIPSDGradientOpacityStop <NSCoding>
{
    double leadOutOpacity;
}

+ (id)doubleOpacityStopWithLocation:(CGFloat)arg1 leadInOpacity:(CGFloat)arg2 leadOutOpacity:(CGFloat)arg3;
+ (void)initialize;
- (id)description;
- (BOOL)isDoubleStop;
- (CGFloat)leadOutOpacity;
- (CGFloat)leadInOpacity;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithLocation:(CGFloat)arg1 leadInOpacity:(CGFloat)arg2 leadOutOpacity:(CGFloat)arg3;

@end

