/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TKStructs.h"

@interface CUIPSDGradientEvaluator : NSObject <NSCoding, NSCopying>
{
    NSArray *colorStops;
    NSArray *colorMidpointLocations;
    NSArray *opacityStops;
    NSArray *opacityMidpointLocations;
    double smoothingCoefficient;
    struct _psdGradientColor fillColor;
    int blendMode;
    double singlePixelDistance;
    struct {
        unsigned int colorEdgePixel:2;
        unsigned int opacityEdgePixel:2;
        unsigned int isDithered:1;
        unsigned int reserved:3;
    } pgeFlags;
}

@property(nonatomic) int blendMode; // @synthesize blendMode;
- (void)customizeForDistance:(CGFloat)arg1;
- (void)setFillCoefficient:(CGFloat)arg1;
- (void)setSmoothingCoefficient:(CGFloat)arg1;
- (void)setOpacityStops:(id)arg1 midpoints:(id)arg2;
- (void)setColorStops:(id)arg1 midpoints:(id)arg2;

- (BOOL)hasDoubleOpacityStops;
- (BOOL)hasDoubleColorStops;
- (BOOL)hasEdgePixel;

- (struct _psdGradientColor)fillColor;
- (CGFloat)fillCoefficient;
- (BOOL)isDithered;
- (CGFloat)smoothingCoefficient;

- (id)opacityMidpointLocations;
- (id)opacityStops;
- (id)colorMidpointLocations;
- (id)colorStops;

- (struct _psdGradientColor)_smoothedGradientColorAtLocation:(CGFloat)arg1;
- (CGFloat)_smoothedInterpolationOfLocation:(CGFloat)arg1 betweenLower:(CGFloat)arg2 upper:(CGFloat)arg3 scaledMidpoint:(CGFloat)arg4;

- (id)initWithColorStops:(id)arg1 colorMidpoints:(id)arg2 opacityStops:(id)arg3 opacityMidpoints:(id)arg4 smoothingCoefficient:(CGFloat)arg5 fillColor:(struct _psdGradientColor)arg6 dither:(BOOL)arg7;
- (id)initWithColorStops:(id)arg1 colorMidpoints:(id)arg2 opacityStops:(id)arg3 opacityMidpoints:(id)arg4 smoothingCoefficient:(CGFloat)arg5 fillCoefficient:(CGFloat)arg6;
- (void)_createOrderedStops:(id *)arg1 midpoints:(id *)arg2 fromStops:(id)arg3 midpoints:(id)arg4 edgePixel:(long long *)arg5;
- (id)_cleanedUpMidpointLocationsFromLocations:(id)arg1;

@end

