/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */


@class CIColor;
@interface CUIColor : NSObject <NSCopying>
{
    CGColorRef *_cgColor;
}

+ (instancetype)colorWithCIColor:(CIColor *)color;
+ (instancetype)colorWithCGColor:(CGColorRef)color;

@property(readonly, nonatomic) CGColorRef CGColor; // @synthesize CGColor=_cgColor;
- (id)initWithCIColor:(id)arg1;
- (id)initWithCGColor:(struct CGColor *)arg1;

@end

