/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TKTypes.h"
#import "TKStructs.h"

typedef struct {
    NSUInteger _field1;
    NSUInteger _field2;
    NSUInteger _field3;
    NSUInteger _field4;
    CUIEffectTuple _field5[35];
} CUIEffectPreset;

@interface CUIShapeEffectPreset : NSObject
{
    CUIEffectTuple _parameterList[35];
    unsigned int _effectIndex[8];
    CGFloat _scaleFactor;
}

+ (NSArray *)requiredEffectParametersForEffectType:(CUIEffectType)arg1;

- (instancetype)initWithEffectScale:(CGFloat)arg1;
- (instancetype)init;
- (instancetype)initWithConstantPreset:(const CUIEffectPreset *)arg1;
- (id)layerEffectsRepresentation; // .caar?
- (NSData *)CUIEffectDataRepresentation;
- (NSUInteger)_parameterCount;

- (void)addBevelEmbossWithHighlightColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 shadowColorRed:(unsigned int)arg5 green:(unsigned int)arg6 blue:(unsigned int)arg7 opacity:(CGFloat)arg8 blur:(int)arg9 soften:(int)arg10;
- (void)addExtraShadowWithColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 blur:(int)arg5 spread:(int)arg6 offset:(int)arg7 angle:(int)arg8;
- (void)addDropShadowWithColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 blur:(int)arg5 spread:(int)arg6 offset:(int)arg7 angle:(int)arg8;
- (void)addOuterGlowWithColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 blur:(int)arg5 spread:(int)arg6;
- (void)addInnerShadowWithColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 blur:(int)arg5 offset:(int)arg6 angle:(int)arg7 blendMode:(unsigned int)arg8;
- (void)addInnerGlowWithColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 blur:(int)arg5 blendMode:(unsigned int)arg6;
- (void)addGradientFillWithTopColorRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 bottomColorRed:(unsigned int)arg4 green:(unsigned int)arg5 blue:(unsigned int)arg6 opacity:(CGFloat)arg7;
- (void)addColorFillWithRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 opacity:(CGFloat)arg4 blendMode:(CGBlendMode)arg5;
- (void)addOutputOpacityWithOpacity:(CGFloat)arg1;
- (void)addShapeOpacityWithOpacity:(CGFloat)arg1;

- (void)appendColorValueRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 forParameter:(CUIEffectParameter)arg4 withEffectType:(CUIEffectType)arg5;
- (void)appendEnumValue:(unsigned int)arg1 forParameter:(CUIEffectParameter)arg2 withEffectType:(CUIEffectType)arg3;
- (void)appendIntValue:(NSUInteger)arg1 forParameter:(CUIEffectParameter)arg2 withEffectType:(CUIEffectType)arg3;
- (void)appendAngleValue:(long long)arg1 forParameter:(CUIEffectParameter)arg2 withEffectType:(CUIEffectType)arg3;
- (void)appendFloatValue:(CGFloat)arg1 forParameter:(CUIEffectParameter)arg2 withEffectType:(CUIEffectType)arg3;
- (void)addColorValueRed:(unsigned int)arg1 green:(unsigned int)arg2 blue:(unsigned int)arg3 forParameter:(CUIEffectParameter)arg4 withNewEffectType:(CUIEffectType)arg5;
- (void)addEnumValue:(unsigned int)arg1 forParameter:(CUIEffectParameter)arg2 withNewEffectType:(CUIEffectType)arg3;
- (void)addIntValue:(NSUInteger)arg1 forParameter:(CUIEffectParameter)arg2 withNewEffectType:(CUIEffectType)arg3;
- (void)addFloatValue:(CGFloat)arg1 forParameter:(CUIEffectParameter)arg2 withNewEffectType:(CUIEffectType)arg3;

- (void)addValue:(CUIEffectValue)arg1 forParameter:(CUIEffectParameter)arg2 withNewEffectType:(CUIEffectType)arg3;
- (void)appendValue:(CUIEffectValue)arg1 forParameter:(CUIEffectParameter)arg2 withEffectType:(CUIEffectType)arg3;
- (void)addValue:(CUIEffectValue)arg1 forParameter:(CUIEffectParameter)arg2 withEffectType:(CUIEffectType)arg3 atEffectIndex:(NSUInteger)arg4;

- (void)getEffectTuples:(CUIEffectTuple **)arg1 count:(NSUInteger *)arg2 atEffectIndex:(NSUInteger)arg3;
- (void)_insertEffectTuple:(CUIEffectTuple)arg1 atEffectIndex:(NSUInteger)arg2;
- (CUIEffectValue)valueforParameter:(CUIEffectParameter)arg1 inEffectAtIndex:(NSUInteger)arg2;

- (CUIEffectType)effectTypeAtIndex:(NSUInteger)arg1;
- (NSUInteger)effectCount;
- (CGFloat)effectScale;

@end


// Not exported
@interface CUIThemeDataEffectPreset : CUIShapeEffectPreset
- (instancetype)initWithEffectData:(const struct cuieffectdata *)arg1 forScaleFactor:(CGFloat)arg2;
@end



