/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/Rendering/CUIThemeGradientDrawing-Protocol.h>
#import <CoreUI/Rendering/PSD/CUIPSDGradientEvaluator.h>
#import <CoreUI/Rendering/CUIColor.h>

@interface CUIThemeGradient : NSObject <CUIThemeGradientDrawing>
{
    CUIPSDGradientEvaluator *gradientEvaluator;
    CGFunctionRef colorShader;
    CGColorSpaceRef colorSpace;
    CGImageRef _gradientImage;
}

- (CGImageRef)_createRadialGradientImageWithWidth:(CGFloat)width height:(CGFloat)height;
- (id)interpolatedColorAtLocation:(CGFloat)location;

- (void)drawFromPoint:(CGPoint)start toPoint:(CGPoint)end options:(NSGradientDrawingOptions)options withContext:(CGContextRef)context;
- (void)drawAngleGradientInRect:(CGRect)rect relativeCenterPosition:(CGPoint)center withContext:(CGContextRef)context;
- (void)drawRadialGradientInRect:(CGRect)rect relativeCenterPosition:(CGPoint)center withContext:(CGContextRef)context;
- (void)drawFromPoint:(CGPoint)from toPoint:(CGPoint)to options:(NSGradientDrawingOptions)options;
- (void)drawInRect:(CGRect)rect angle:(CGFloat)angle;
- (void)drawInRect:(CGRect)rect angle:(CGFloat)angle withContext:(CGContextRef)contex;

- (CGFunctionRef)colorShader;
- (CGFunctionRef)_newColorShaderForDistance:(CGFloat)distance;

- (CGBlendMode)blendMode;
- (CUIColor *)fillColor;
- (BOOL)isDithered;
- (CGFloat)smoothingCoefficient;

- (NSArray<NSNumber *> *)opacityLocations;
- (NSArray<NSNumber *> *)opacityStops;
- (NSArray<NSNumber *> *)colorLocations;
- (NSArray<CUIColor *> *)colorStops;

- (CUIColor *)_colorFromPSDGradientColor:(struct _psdGradientColor)arg1;

- (instancetype)initWithColors:(NSArray *)colors
                colorlocations:(NSArray *)colorLocations
                colorMidpoints:(NSArray *)colorMidpoints
                     opacities:(NSArray *)opacities
              opacityLocations:(NSArray *)opacityLocations
              opacityMidpoints:(NSArray *)opacityMidpoints
          smoothingCoefficient:(CGFloat)smoothing
                     fillColor:(CUIColor *)fillColor
                    colorSpace:(CGColorSpaceRef)colorSpace
                        dither:(BOOL)dithered;

- (instancetype)initWithColors:(NSArray *)colors
                colorlocations:(NSArray *)colorLocations
                colorMidpoints:(NSArray *)colorMidpoints
                     opacities:(NSArray *)opacities
              opacityLocations:(NSArray *)opacityLocations
              opacityMidpoints:(NSArray *)opacityMidpoints
          smoothingCoefficient:(CGFloat)smoothing
                     fillColor:(CUIColor *)fillColor
                    colorSpace:(CGColorSpaceRef)colorSpace;

- (instancetype)_initWithGradientEvaluator:(CUIPSDGradientEvaluator *)evaluator colorSpace:(CGColorSpaceRef)colorSpace;

- (NSArray<__kindof CUIPSDGradientColorStop *> *)_psdGradientColorStopsWithColors:(NSArray *)colors locations:(NSArray *)locations colorSpace:(CGColorSpaceRef)colorSpace;
- (struct _psdGradientColor)_psdGradientColorWithColor:(id)arg1 colorSpace:(CGColorSpaceRef)colorSpace;
- (NSArray<__kindof CUIPSDGradientOpacityStop *> *)_psdGradientOpacityStopsWithOpacities:(NSArray *)opacities locations:(NSArray *)locations;

@end

